### ISSUE TITLE
Docker image at docker hub

### ISSUE THREAD

**Issue by moi90** [morphocluster/morphocluster#27]
https://docs.docker.com/docker-hub/builds/

**Comment by joefutrelle** [comment]
Hi, I'm wondering if you have plans to provide an ARM architecture image as well?

**Comment by moi90** [comment]
Hi @joefutrelle, not at the moment, no. Currently, the image building and uploading is completely manual. Maybe we will switch to automated builds in the future. Then, we might also consider builds for different architectures.

**Comment by singhsaluja** [comment]
Can you please provide a link to the image pushed on Dockerhub? My attempt to build the image have been failing. It would make it easier to just pull the prebuilt container. Thanks!

**Comment by moi90** [comment]
@singhsaluja You can use the pre-build image by replacing this

```yaml
services:
  morphocluster:
    build:
      context: .
      dockerfile: docker/morphocluster/Dockerfile
```

in your `docker-compose.yml` with this:

```yaml
services:
  morphocluster:
    image: morphocluster/morphocluster:0.2.1
```
