### ISSUE TITLE
Shorten text in member header

### ISSUE THREAD

**Issue by moi90** [morphocluster/morphocluster#7]
```css
element {
    text-overflow: ellipsis;
    overflow: hidden;
    white-space: nowrap;
}
```
