### ISSUE TITLE
Use CSS to enhance images

### ISSUE THREAD

**Issue by moi90** [morphocluster/morphocluster#78]
Images can be altered on the fly using CSS:

```css
img {
  filter: brightness(200%) contrast(199%) saturate(200%) invert();
}
```

We should have a UI for that.
