### ISSUE TITLE
Make object image fill width of card

### ISSUE THREAD

**Issue by moi90** [morphocluster/morphocluster#8]
```css
.member-body.oneImage img[data-v-61bc16d0] {
    max-width: 100%;
    width: unset;
    max-height: 150px;
    margin: 0 auto;
    display: block;
    width: 100%;
}
```
